version: "3.8"

services:
  web:
    image: jekyll/jekyll
    container_name: web.praguedash
    command: jekyll serve --force_polling
    ports:
      - 4000:4000
    volumes:
      - ./web:/srv/jekyll
