version: "3.8"

services:
  docs:
    image: jekyll/jekyll
    container_name: docs.praguedash
    command: jekyll serve --force_polling
    ports:
      - 4000:4000
    volumes:
      - ./docs:/srv/jekyll
