version: "3.8"

services:
  docs:
    image: jekyll/jekyll:pages
    container_name: docs.praguedash
    command: jekyll serve
    ports:
      - 4000:4000
    volumes:
      - ./docs:/srv/jekyll
    environment:
      JEKYLL_UID: 1008
      JEKYLL_GID: 1008
