import { INestApplication } from "@nestjs/common";
import { OpenAPIObject, SwaggerModule } from "@nestjs/swagger";
import { SwaggerUiOptions } from "@nestjs/swagger/dist/interfaces/swagger-ui-options.interface";

// TODO: share this file with app/backend, geocoding and bundler

/**
 * App agnostic function to add Swagger UI to a NestJS application. Adds niceties to standard SwaggerModule.setup().
 */
export function addSwaggerUI(
  path: string,
  app: INestApplication,
  openapiDocument: OpenAPIObject,
  swaggerUiOptions: SwaggerUiOptions = {},
) {
  path = normalizePathPrefix(path);

  // SwaggerModules does not add the OpenAPI paths for the paths generated by itself, so we need to add them manually
  addOpenapiPaths(path, openapiDocument);

  function openapiTagSorter(a: string, b: string) {
    if (a === "Root") return -1;
    if (b === "Root") return 1;
    return a.localeCompare(b);
  }

  // because standard operation sorts dashes before slashes
  // ie /user-profile comes between /user and /user/{id}
  // this function sorts by path parts
  // ie /user-profile comes after /user and /user/{id}
  function operationsSorter(a: Map<"path" | "method", string>, b: Map<"path" | "method", string>) {
    const aParts = a.get("path")?.split("/");
    const bParts = b.get("path")?.split("/");

    const methodsOrder = ["options", "get", "query", "post", "put", "patch", "delete"];

    if (!aParts || !bParts) return 0;

    while (true) {
      // paths are same, sort by method
      if (!aParts.length && !bParts.length) {
        return methodsOrder.indexOf(a.get("method")!) - methodsOrder.indexOf(b.get("method")!);
      }

      // shorter path first
      if (!aParts.length) return -1;
      if (!bParts.length) return 1;

      // variable path parts at the end
      if (aParts[0].startsWith("{") && !bParts[0].startsWith("{")) return 1;
      if (!aParts[0].startsWith("{") && bParts[0].startsWith("{")) return -1;

      const result = aParts.shift()!.localeCompare(bParts.shift()!);
      if (result !== 0) return result;
    }
  }

  SwaggerModule.setup(path, app, openapiDocument, {
    swaggerOptions: {
      tagsSorter: openapiTagSorter,
      operationsSorter: operationsSorter,
      persistAuthorization: true,
      showCommonExtensions: true,
      displayOperationId: true,
      ...swaggerUiOptions,
    },
  });
}

/**
 * Add OpenAPI paths to the document
 */
function addOpenapiPaths(path: string, document: OpenAPIObject) {
  const paths = {
    [path]: {
      get: {
        tags: ["Root"],
        summary: "This SwaggerUI page",
        operationId: "viewSwaggerUI",
        parameters: [],
        responses: {
          "200": {
            description: "OpenAPI document",
            content: {
              "application/html": {
                schema: {
                  type: "string",
                },
              },
            },
          },
        },
      },
    },
    [path + "-json"]: {
      get: {
        tags: ["Root"],
        summary: "The OpenAPI document in JSON",
        operationId: "getOpenAPIJSON",
        parameters: [],
        responses: {
          "200": {
            description: "OpenAPI document",
            content: {
              "application/json": {
                schema: {
                  type: "string",
                },
              },
            },
          },
        },
      },
    },
    [path + "-yaml"]: {
      get: {
        tags: ["Root"],
        summary: "The OpenAPI document in YAML",
        operationId: "getOpenAPIYAML",
        parameters: [],
        responses: {
          "200": {
            description: "OpenAPI document",
            content: {
              "application/yaml": {
                schema: {
                  type: "string",
                },
              },
            },
          },
        },
      },
    },
  };
  Object.assign(document.paths, paths);
}

function normalizePathPrefix(path?: string) {
  if (!path) return "";

  return path
    ?.replace(/\/$/, "") // remove trailing slash
    ?.replace(/^([^/])/, "/$1"); // ensure leading slash
}
